### ISSUE TITLE
Linux web app service with netcore 3.0 does not support auto heal

### ISSUE THREAD

**Issue by rolandh** [Azure/Azure-AppServices-Diagnostics#357]
I'm not sure where the correct place to raise this issue is so I'll try here, if not could someone refer me to the correct project.

The issue is Windows App Service/Webapp supports auto heal. Linux web apps do not support it. What is required to get this functionality added? I'd be happy to assist with development or testing.

Here is a screenshot demonstrating the feature that is missing. Without this functionality we have to rely on alerts and manual reboots if an out of memory exception or similar occurs.

![image](https://user-images.githubusercontent.com/1109554/70481531-c8d5f000-1b32-11ea-8ed6-f321631813e4.png)

**Comment by ShekharGupta1988** [comment]
https://azure.github.io/AppService/2021/04/21/Announcing-Autoheal-for-Azure-App-Service-Linux.html
