### ISSUE TITLE
Unable to to capture network traces for a regular web app hosted on the PremiumV2 ASP

### ISSUE THREAD

**Issue by motasem13** [Azure/Azure-AppServices-Diagnostics#5]
I have an issue with to capturing a network traces for a regular web app hosted on the PremiumV2 ASP,
i had the following error message:
Error - This tool is supported only on Dedicated SKU's

Repro Steps: scale any regular web app to PremV2 asp and try to capture network traces through Diagnose and solve a problem Blade.

**Comment by puneetg1983** [comment]
I only asked him to open this bug so I don't forget. will check it soon

**Comment by puneetg1983** [comment]
This is resolved so closing the issue...
