### ISSUE TITLE
"Diagnose and solve problems" view not working for apps in the new PremiumV3 plan

### ISSUE THREAD

**Issue by tommye** [Azure/Azure-AppServices-Diagnostics#584]
I have created a new P2V3 app service plan. I have deployed my app to the new plan and everything seems to be working fine, except for the "Diagnose and solve problems" view. It shows only the header text and the search field. For instance, I am unable to open the application event log.

![Capture](https://user-images.githubusercontent.com/7523419/95902680-69b9bb00-0d95-11eb-8bbd-69c33db51581.PNG)

**Comment by ShekharGupta1988** [comment]
Hi @tommye ,
This should be fixed. Please check and let us know if you are still facing the issue.
Adding @cindylovescoding as well to the thread
