### ISSUE TITLE
Unable to set alert for High Outbound TCP Connections Detected for App Service Web App

### ISSUE THREAD

**Issue by StoyanShopov** [Azure/Azure-AppServices-Diagnostics#758]
Hello,

Recently we've detected that we have high outbound TCP connections via Diagnose and Solve problems and it was an internal problem in our app.

Now we want to set up a rule (for App Service Web App) whenever we exceed our TCP connections (per plan) or reach some threshold.

Is it possible to create such a rule?

**Comment by hforeste** [comment]
Hi @StoyanShopov ,

Have you tried looking at the metrics you can monitor on the app service plan? You can create an alert rule based on `Established Socket Count for Outbound Requests` as well as `Time Wait Socket Count for Outbound Requests`
